.MODEL SMALL
.STACK 100H
.DATA
    arr db 1,2,3,4,5
    arr2 dw 3,4,5,6,7
    W DB 5 DUP (0) ;W DB 0,0,0,0,0
    ENDL DB 0AH,0DH,'$'
.CODE
MAIN PROC
    MOV AX,@DATA
    MOV DS,AX

    ;OFFSET                 ;SEGMENT
    ;BX -> BASE REGISTER       DS
    ;SI -> SOURCE INDEX        DS
    ;DI -> DESTINATION INDEX   DS
    ;BP -> BASE POINTER        SS

    ;LEA SI,ARR
    ;MOV AX,SI     ; SI IS 16 BITS
    ;MOV AL,[SI]    ;REGISTER INDIRECT METHOD

    MOV CX,5
    LEA SI,ARR    ;WE CAN SKIP THIS LINE SINCE SI BY DEFAULT LOADS THE ADDRESS OF THE FIRST ARRAY
    PRINT:
    XOR AX,AX
    MOV AL,[SI]
    CALL OUTDEC ;OUTDEC PRINTS THE WHOLE AX
    INC SI      ;IN EACH INCREMENT SI ONLY ADDS ONE BYTE
    MOV AH,9
    LEA DX,ENDL
    INT 21H
    LOOP PRINT
;NORMALLY THE VALUE OF SI IS 0. SO SI ALWAYS HOLDS THE FIRST ADDRESS OF THE DATA SEGMENT

    MOV CX,5
    LEA SI,ARR2
    PRINT_:
    XOR AX,AX
    MOV AX,[SI]
    CALL OUTDEC 
    INC SI      ;IN EACH INCREMENT SI ONLY ADDS ONE BYTE AND HERE WE HAVE TO MOVE 2 BYTES
    INC SI
    MOV AH,9
    LEA DX,ENDL
    INT 21H
    LOOP PRINT_        
        
        
    MOV AH,4CH
    INT 21H
MAIN ENDP
INCLUDE INDEC.ASM
INCLUDE OUTDEC.ASM
END MAIN
