.MODEL SMALL
.STACK 100H
.DATA
MSG1 DB 'Enter text: $'
MSG2 DB 0DH,0AH,'Reversed words: $'
TEXT DB 200 DUP('$')
BUFFER DB 50 DUP('$')
.CODE

MAIN PROC
    MOV AX,@DATA
    MOV DS,AX
    LEA DX,MSG1
    MOV AH,9
    INT 21H
    LEA SI,TEXT
INPUT:
    MOV AH,1
    INT 21H
    CMP AL,0DH
    JE INPUT_END
    MOV [SI],AL
    INC SI
    JMP INPUT
INPUT_END:
    MOV BYTE PTR [SI],'$'
    LEA DX,MSG2
    MOV AH,9
    INT 21H
    LEA SI,TEXT
    LEA DI,BUFFER
    XOR CX,CX
NEXT_CHAR:
    MOV AL,[SI]
    CMP AL,'$'
    JE LAST_WORD
    CMP AL,' '
    JE SPACE_FOUND
    MOV [DI],AL
    INC DI
    INC CX
    INC SI
    JMP NEXT_CHAR
SPACE_FOUND:
    CALL REVERSE
    MOV DL,' '
    MOV AH,2
    INT 21H
    LEA DI,BUFFER
    XOR CX,CX
    INC SI
    JMP NEXT_CHAR
LAST_WORD:
    CALL REVERSE
    MOV AH,4CH
    INT 21H
MAIN ENDP

REVERSE PROC
    CMP CX,0
    JE REVERSE_END
    PUSH SI
    LEA SI,BUFFER
    ADD SI,CX
    DEC SI
PRINT_WORD:
    MOV DL,[SI]
    MOV AH,2
    INT 21H
    DEC SI
    LOOP PRINT_WORD
    POP SI
REVERSE_END:
    RET
REVERSE ENDP
END MAIN